// types.js - 类型定义和枚举

// 考试阶段
export const ExamStage = {
  ONBOARDING: 'ONBOARDING',
  MODE_SELECTION: 'MODE_SELECTION',
  EXAM_TYPE_SELECTION: 'EXAM_TYPE_SELECTION',
  PRACTICE_PART_SELECTION: 'PRACTICE_PART_SELECTION',
  PART1_SELF_INTRO: 'PART1_SELF_INTRO',
  PART2_SHORT_QA: 'PART2_SHORT_QA',
  PART3_PREP: 'PART3_PREP',
  PART3_PRESENTATION: 'PART3_PRESENTATION',
  PART4_PAIR_DISCUSSION: 'PART4_PAIR_DISCUSSION',
  PART5_IN_DEPTH_QA: 'PART5_IN_DEPTH_QA',
  PROCESSING: 'PROCESSING',
  REPORT: 'REPORT',
  HISTORY: 'HISTORY'
};

// 考试模式
export const ExamMode = {
  REAL: 'REAL',
  SIMULATION: 'SIMULATION'
};

// 考试类型
export const ExamType = {
  FULL_EXAM: 'FULL_EXAM',
  PRACTICE: 'PRACTICE'
};

// 练习部分
export const PracticePart = {
  PART1: 'PART1',
  PART2: 'PART2',
  PART3: 'PART3',
  PART4: 'PART4',
  PART5: 'PART5'
};
